name: Nix Cache Fill

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: sosumappu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build nixpkgs-unstable packages
        run: |
          nix build \
              nixpkgs/nixpkgs-unstable#deno \
              nixpkgs/nixpkgs-unstable#direnv \
              nixpkgs/nixpkgs-unstable#notmuch \
              nixpkgs/nixpkgs-unstable#aerc \
              nixpkgs/nixpkgs-unstable#rustc \
              --no-link --print-build-logs

      - name: Build yazi
        run: nix build github:sxyazi/yazi#yazi --no-link --print-build-logs

      - name: Build atuin
        run: nix build github:atuinsh/atuin#atuin --no-link --print-build-logs

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = aarch64-linux

      - uses: cachix/cachix-action@v17
        with:
          name: sosumappu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build nixpkgs-unstable packages (aarch64)
        run: |
          nix build \
              --system aarch64-linux \
              nixpkgs/nixpkgs-unstable#deno \
              nixpkgs/nixpkgs-unstable#direnv \
              nixpkgs/nixpkgs-unstable#notmuch \
              nixpkgs/nixpkgs-unstable#aerc \
              nixpkgs/nixpkgs-unstable#rustc \
              --no-link --print-build-logs

      - name: Build yazi (aarch64)
        run: |
          nix build --system aarch64-linux \
              github:sxyazi/yazi#yazi --no-link --print-build-logs

      - name: Build atuin (aarch64)
        run: |
          nix build --system aarch64-linux \
              github:atuinsh/atuin#atuin --no-link --print-build-logs

  build-darwin:
    runs-on: macos-15-intel
    steps:
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v17
        with:
          name: sosumappu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build nixpkgs-unstable packages
        run: |
          nix build \
              nixpkgs/nixpkgs-unstable#deno \
              nixpkgs/nixpkgs-unstable#direnv \
              nixpkgs/nixpkgs-unstable#notmuch \
              nixpkgs/nixpkgs-unstable#rustc \
              --no-link --print-build-logs

      - name: Build yazi
        run: nix build github:sxyazi/yazi#yazi --no-link --print-build-logs

      - name: Build atuin
        run: nix build github:atuinsh/atuin#atuin --no-link --print-build-logs
